### PR TITLE
fix: Pass classes to editor element

### PR DESCRIPTION
**Pull request by knd775**

### CODE REVIEW

**Comment by sibiraj-s** [comment]
PR looks good, I'll double check once if there won't be any conflicts with tiptap classes, if used like this. Just a doubt.

Meanwhile if required now, I'd recommend using https://tiptap.dev/docs/editor/api/editor#editorprops if classes not dynamic

**Comment by rice-cracker-dev** [comment]
@sibiraj-s any update on this PR?

**Comment by sibiraj-s** [comment]
My bad i forgot. Will check and merge.

**Review by sibiraj-s — APPROVED** [review]

**Comment by sibiraj-s** [comment]
Available in v2.1.0, note this passes the class to the editor container. Not the editor itself, to set the class on editor. You would still need to do via editor props https://tiptap.dev/docs/editor/api/editor#editorprops

**Comment by knd775** [comment]
> Available in v2.1.0, note this passes the class to the editor container. Not the editor itself, to set the class on editor. You would still need to do via editor props [tiptap.dev/docs/editor/api/editor#editorprops](https://tiptap.dev/docs/editor/api/editor#editorprops)

Yep, this is what I was going for. This was something specific we needed when switching from our own solution to this library. Thanks for merging!

**Pull request merged**
